// Production build for the published CLI. esbuild bundles the `cmpatch` bin into a
// single self-contained file, inlining our own source AND the private
// `@codemagic/patch-shared` workspace (resolved from its TypeScript source via the
// alias below) so the shipped package has no unpublishable workspace dependency.
//
// Every real npm dependency stays external (installed from the registry) — only
// our first-party code is bundled. The output lives at dist/cmpatch.js (one level
// under dist/) so version.ts's `join(__dirname, "..", "package.json")` still
// resolves to the package root, exactly as it did under the old tsc layout.

import { readFile, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const cliRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(await readFile(resolve(cliRoot, "package.json"), "utf8"));

// Wipe stale outputs from older build layouts (the previous per-module tsc
// output, an old dist/bin/ layout, and bundles left over from earlier product
// names) before regenerating. package.json publishes the whole dist/, so without
// this the tarball would ship those dead, wrong-brand files. dist/ is gitignored
// and is fully regenerated by the esbuild call below.
await rm(resolve(cliRoot, "dist"), { recursive: true, force: true });

await build({
  entryPoints: [resolve(cliRoot, "src/bin/cmpatch.ts")],
  outfile: resolve(cliRoot, "dist/cmpatch.js"),
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  sourcemap: true,
  // Keep published runtime deps external; bundle only first-party code.
  external: Object.keys(pkg.dependencies ?? {}),
  alias: {
    "@codemagic/patch-shared": resolve(cliRoot, "../shared/src/index.ts"),
  },
  logLevel: "info",
});
