#!/bin/bash
# Regenerates libs/zstd/codemagic_patch_zstd_prefix.h.
#
# WHY: the SDK vendors zstd (decompress build) as plain C with default-visibility,
# un-prefixed symbols (ZSTD_*, HUF_*, FSE_*, XXH*, ...). If the host app links
# another copy of zstd/xxhash (commonly bundled inside ML / media / networking
# binary frameworks), the linker can bind our calls to the other copy's
# ABI-incompatible implementation and silently corrupt OTA extraction — the same
# failure mode as the SSZipArchive-vs-MediaPipe minizip clash. We isolate every
# exported zstd symbol behind a CMPATCH_ prefix so no collision is possible,
# regardless of link order.
#
# The generated header is force-included (-include) into every TU that defines or
# calls zstd (see CodemagicPatchClient.podspec and android/CMakeLists.txt), so
# definitions and call sites are renamed consistently.
#
# Re-run this after upgrading the vendored zstd:  bash libs/zstd/gen_zstd_prefix.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"          # .../client/libs/zstd
ZSTD_DIR="$HERE"
LIB="$ZSTD_DIR/lib"
OUT_HEADER="$ZSTD_DIR/codemagic_patch_zstd_prefix.h"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

CC="$(xcrun -f clang)"
SYSROOT="$(xcrun --show-sdk-path)"
# Same defines the real build uses. XXH_NAMESPACE=CMPATCH_ pre-namespaces xxhash so
# its symbols are isolated and excluded from the generated #defines (defining them
# would clash with xxhash.h's own XXH_NAME2 token-paste macros).
FLAGS=(-c -O2 -arch arm64 -isysroot "$SYSROOT"
       -DZSTD_DISABLE_ASM=1 -DZSTD_LIB_DEPRECATED=0 -DXXH_NAMESPACE=CMPATCH_
       -I"$LIB" -I"$LIB/common" -I"$LIB/decompress")

# Must match the zstd sources compiled by the podspec / CMakeLists (decompress build).
FILES=(
  common/entropy_common.c common/error_private.c common/fse_decompress.c
  common/xxhash.c common/zstd_common.c
  decompress/huf_decompress.c decompress/zstd_ddict.c
  decompress/zstd_decompress.c decompress/zstd_decompress_block.c
)

for f in "${FILES[@]}"; do
  "$CC" "${FLAGS[@]}" "$LIB/$f" -o "$WORK/$(echo "$f" | tr / _).o"
done

# All defined external symbols (nm type letter is not 'U'); strip Mach-O leading '_'.
# Exclude:
#  - CMPATCH_*  : xxhash, already namespaced via XXH_NAMESPACE
#  - XXH*     : handled by XXH_NAMESPACE; redefining clashes with xxhash.h macros
#  - *_isError: zstd #undefs ZSTD_isError and #defines FSE_/HUF_isError to the inline
#               ERR_isError, so a macro rename can't stick and only warns. These are
#               stateless, ABI-stable error-code predicates (unsigned(size_t)); a
#               collision with another zstd copy is behaviorally inert.
SYMS="$(nm -g "$WORK"/*.o \
  | awk '$2 != "U" && $3 ~ /^_/ { print substr($3, 2) }' \
  | sort -u \
  | grep -vE '^CMPATCH_' \
  | grep -vE '^_?XXH' \
  | grep -vE '^(ZSTD|FSE|HUF)_isError$' || true)"

COUNT="$(printf '%s\n' "$SYMS" | grep -c . || true)"

{
  echo "// AUTO-GENERATED by libs/zstd/gen_zstd_prefix.sh — DO NOT EDIT BY HAND."
  echo "// Isolates the vendored zstd (decompress build) so its exported C symbols"
  echo "// cannot collide with another copy of zstd/xxhash linked into the host app."
  echo "// Background: a sibling SDK shipped two copies of minizip (SSZipArchive vs"
  echo "// MediaPipe); the linker bound calls to the wrong ABI and corrupted OTA"
  echo "// extraction. zstd/xxhash are even more commonly vendored, so we prefix here."
  echo "//"
  echo "// Force-included (-include) into every translation unit that defines OR calls"
  echo "// zstd, so definitions and call sites are renamed consistently."
  echo "//"
  echo "// Deliberately NOT renamed: ZSTD_isError / FSE_isError / HUF_isError. zstd"
  echo "// #undefs/#defines these to the inline ERR_isError internally, so a macro"
  echo "// rename cannot stick. They are stateless, ABI-stable error-code predicates"
  echo "// (unsigned(size_t)), so a collision with another zstd copy is behaviorally"
  echo "// inert. Every stateful/struct/streaming function IS renamed."
  echo "#ifndef CODEMAGIC_PATCH_ZSTD_PREFIX_H"
  echo "#define CODEMAGIC_PATCH_ZSTD_PREFIX_H"
  echo ""
  echo "// xxhash: namespace all of its symbols (XXH32 -> CMPATCH_XXH32, ...). Must be"
  echo "// defined before xxhash.h is processed; this header is force-included first."
  echo "#ifndef XXH_NAMESPACE"
  echo "#define XXH_NAMESPACE CMPATCH_"
  echo "#endif"
  echo ""
  printf '%s\n' "$SYMS" | while IFS= read -r s; do
    [ -n "$s" ] && echo "#define $s CMPATCH_$s"
  done
  echo ""
  echo "#endif // CODEMAGIC_PATCH_ZSTD_PREFIX_H"
} > "$OUT_HEADER"

echo "Generated $OUT_HEADER"
echo "Renamed (non-xxhash) symbols: $COUNT"
